CREATE DATABASE IF NOT EXISTS shopmanager CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shopmanager;

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 username VARCHAR(80) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role ENUM('admin','cashier') NOT NULL DEFAULT 'cashier',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(180) NOT NULL,
 barcode VARCHAR(100) UNIQUE NULL,
 buy_price DECIMAL(12,2) NOT NULL DEFAULT 0,
 sell_price DECIMAL(12,2) NOT NULL DEFAULT 0,
 stock INT NOT NULL DEFAULT 0,
 min_stock INT NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 INDEX(stock)
);

CREATE TABLE customers (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 phone VARCHAR(50) NULL,
 address VARCHAR(255) NULL,
 debt DECIMAL(12,2) NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sales (
 id INT AUTO_INCREMENT PRIMARY KEY,
 customer_id INT NULL,
 user_id INT NULL,
 total DECIMAL(12,2) NOT NULL,
 profit DECIMAL(12,2) NOT NULL,
 paid DECIMAL(12,2) NOT NULL DEFAULT 0,
 debt DECIMAL(12,2) NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE SET NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE sale_items (
 id INT AUTO_INCREMENT PRIMARY KEY,
 sale_id INT NOT NULL,
 product_id INT NOT NULL,
 qty INT NOT NULL,
 price DECIMAL(12,2) NOT NULL,
 cost DECIMAL(12,2) NOT NULL,
 FOREIGN KEY(sale_id) REFERENCES sales(id) ON DELETE CASCADE,
 FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE RESTRICT
);

CREATE TABLE expenses (
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(180) NOT NULL,
 amount DECIMAL(12,2) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users(name,username,password,role)
VALUES ('مدير النظام','admin','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC1q7rQ9qj4d6p0e6Y6','admin');
-- كلمة المرور التجريبية: password
-- غيّرها بعد أول تسجيل دخول.
